# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='account',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='account',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.AlterModelTable(
            name='account',
            table='racchai_user',
        ),
    ]
