# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170608_0741'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='api_user',
        ),
    ]
