# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_account_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
