# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20170611_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='detail',
            new_name='user_detail',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
