# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20170611_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='delete',
        ),
    ]
